### PR TITLE
Add PEP-561 with py.typed

### PR DESCRIPTION
**Pull request by JCHacking**
Added the py.typed file so that when someone uses this library they can parse their typed with mypy

This was pointed out in #93

### CODE REVIEW

**Comment by saghul** [comment]
Is there a way to test this?

**Comment by JCHacking** [comment]
The way I realized it was when I wanted to use a library that I had made from another one. So I understand that you can not test from the same library.

**Comment by saghul** [comment]
I see. I think you need to add it to MANIFEST.in though, so it's added to the package when building it, otherwise it will be skipped.

**Comment by JCHacking** [comment]
I have tried to generate the wheel and have not seen any problem without adding it to the manifest.in
I think that as it is inside the package it understands that it has to be included.

**Comment by JCHacking** [comment]
@saghul I have already added it, if you can confirm me that this is correct (I have never used MANIFEST.in)

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Cheers!

**Pull request merged**
