### PR TITLE
Remove loop= param from asyncio.sleep() to fix tests on Python 3.10

### LINKED ISSUE #95: Python 3.10 test failure: ERROR: test_future_cancel: TypeError: sleep() got an unexpected keyword argument 'loop'
When running tests with Python 3.10.0b1:
```
======================================================================
ERROR: test_future_cancel (__main__.DNSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/aiodns/tests.py", line 122, in test_future_cancel
    self.loop.run_until_complete(coro())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/tmp/aiodns/tests.py", line 119, in coro
    await asyncio.sleep(0.1, loop=self.loop)
TypeError: sleep() got an unexpected keyword argument 'loop'
```

### PR DESCRIPTION
**Pull request by mgorny**
Fixes #95

### CODE REVIEW

**Comment by mgorny** [comment]
I've also attempted enabling GHA testing on 3.10.

**Comment by saghul** [comment]
Looks like we need to install the wheel package to make sure building works.

**Comment by mgorny** [comment]
Yeah, I'm guessing this is because either some of the low-level stuff (pip?) or GHA hasn't been yet all synced for 3.10 deprecations.

**Comment by mgorny** [comment]
Windows seems to be unhappy but I don't really know how to fix it.

**Comment by saghul** [comment]
Let's exclude it for now. Linux and macOS pass, which is a good indication :-)

I think you can add a "excludes" section to the build matrix to skip 3.10 on Windows.

**Comment by mgorny** [comment]
Let's try that but I think the wheel install stage could be causing the hangs on 3.8/3.9 jobs too.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Not sure why Windows is getting stuck on Python 3.8/3.9 but that's not related to your PR. Merged!

**Pull request merged**
