### PR TITLE
Require new pycares 2.0.0

### PR DESCRIPTION
**Pull request by VSSRS**
Enables proper querying of fragmented TXT records, etc.

### CODE REVIEW

**Comment by saghul** [comment]
pycares 2.0.0 doesn't yet use the new API for handling the chunked TXT records. Do you have a record I can test with?

**Comment by VSSRS** [comment]
One random example I found in my data:
```
;; QUESTION SECTION:
;museumofplay.org.		IN	TXT

;; ANSWER SECTION:
museumofplay.org.	3548	IN	TXT	"v=spf1" "a:mail.museumofplay.org" "a:relay.museumofplay.org" "ip4:63.139.104.26" "ip4:63.139.104.5" "~all"
```

**Comment by saghul** [comment]
Thanks! I'll take care of if when I have some time. If you feel like sending a PR, please feel free to do so.

**Comment by VSSRS** [comment]
Now that the necessary code is available in Pycares 2.1.0, can we update aiodns to integrate this as well? 
Thanks.

**Comment by saghul** [comment]
I haven't published it yet. But regardless, I don't see the need to update the requirement. Currently it depends on pycares >= 1.0.0, which is API compatible with 2.X, so if you get the latest it will continue to work and the requirement will be fulfilled anyway.

I chose to use >= to avoid changes like this on purpose :-)

**Comment by VSSRS** [comment]
Agreed. Thanks!

**Pull request closed without merging**
