### PR TITLE
fix #57: only depend on typing for python < 3.7

### LINKED ISSUE #57: `install_requires` collides with `typing` for the standard library
Hi,

The `install_requires` section in `setup.py` contains `typing` dependency, which at least on my Python 3.7 collides with the standard `typing` and produces false-positive warnings in IDE.

Should it perhaps use [environment markers](https://www.python.org/dev/peps/pep-0496/) to avoid installing the 3rd-party `typing` on the latest Python?

Regards,
Pavel

### PR DESCRIPTION
**Pull request by arthurdarcet**

### CODE REVIEW

**Comment by saghul** [comment]
Thank you!

**Comment by arthurdarcet** [comment]
Could you release a new version for this ? aiodns is broken on py3.7, and it means aiohttp does not install anymore on py3.7…

**Comment by saghul** [comment]
Done, 2.0.0b1 is out! Btw, how come was it broken? Travis tests passed on 3.7 too.

**Comment by saghul** [comment]
Oh, weird. Anyway, should be fixed now!

**Pull request merged**
