### PR TITLE
Converted Type Annotations to Py3 syntax

### PR DESCRIPTION
**Pull request by mimi89999**
Type annotations are very long for this project. Not sure what to do about that. Maybe they should be defined somewhere else?

### CODE REVIEW

**Comment by saghul** [comment]
Thank you!

However this seems to break in Python 3.5: https://travis-ci.org/saghul/aiodns/jobs/624322207?utm_medium=notification&utm_source=github_status

**Comment by mimi89999** [comment]
I think that it would be very inconsistent to keep variable annotations as comments and use Python3.6 syntax for function annotations. How long will Python3.5 be supported by _aiodns_?

**Comment by mimi89999** [comment]
I reverted variable annotations.

**Comment by saghul** [comment]
> How long will Python3.5 be supported by _aiodns_?

For the foreseable future. Ubuntu 16.04, which is LTS has 3.5, for example.

**Comment by saghul** [comment]
Merged, thank you!

**Pull request merged**
