### PR TITLE
implement gethostbyaddr for reverse lookups

### PR DESCRIPTION
**Pull request by antonagestam**
Hi,

Thanks for this package! I have the need to make async reverse lookups.

I was able to add the `gethostbyaddr` from the pycares package here pretty quickly. Is this something that is interesting for you to support? If so please tell me if you need me to make changes to the testing or flesh out the documentation a bit more.

Please note that I don't know that much about the underlying mechanisms here.

### CODE REVIEW

**Comment by saghul** [comment]
@antonagestam Thank you! The patch looks solid and all I need to do is remove Python 3.3 from Travis.

I'll try to get some time in the next few weeks to get a new release out.

Cheers!

**Comment by antonagestam** [comment]
Cool! If you want to I can remove Python 3.3 in another commit to this PR as well.

**Comment by MMquant** [comment]
Merge please! :)

**Comment by antonagestam** [comment]
I pushed a PR https://github.com/saghul/aiodns/pull/48 that removes 3.3 (tried adding 3.7 but travis failed to download so let's look at that later).

**Comment by antonagestam** [comment]
It's officially a pull request party 🥳Opened another one that both removes 3.3 and adds 3.7: https://github.com/saghul/aiodns/pull/49

**Pull request merged**
